-
  name: 'MarkdownContent Catchall'
  uriPattern: '{path}'
  defaults:
    '@package': 'Scriptme.MarkdownContent'
    '@controller': 'Standard'
    '@action': 'index'
    '@format': 'html'

-
 name: 'MarkdownContent fallback'
 uriPattern: ''
 defaults:
   '@package': 'Scriptme.MarkdownContent'
   '@controller': 'Standard'
   '@action': 'index'
   '@format': 'html'