-
  name: 'Catchall'
  uriPattern: '{path}(.html)'
  defaults:
    '@package': 'Scriptme.MarkdownContent'
    '@controller': 'Standard'
    '@action': 'index'
    '@format': 'html'
  routeParts:
    path:
      handler: Scriptme\MarkdownContent\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: true